Restrev/config/routes.rb
Restrev::Application.routes.draw do
  resources :users
  resources :restaurants do
    resources :ratings, :only => [:create, :update]
  end
  resources :ratings, :except => [:create, :update]

  root :to => 'restaurants#index'

end

Restrev/app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :user_id, :restaurant_id, :stars, :details

  validates_presence_of :user_id, :restaurant_id, :stars

  validates_uniqueness_of :restaurant_id, :scope => :user_id

  validates :stars, :inclusion => 1..5

  belongs_to(
      :rater,
      :primary_key => :id,
      :foreign_key => :user_id,
      :class_name => "User"
  )

  belongs_to(
      :rated,
      :primary_key => :id,
      :foreign_key => :restaurant_id,
      :class_name => "Restaurant"
  )

end

Restrev/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :name, :genre

  validates_presence_of :name

  has_many :ratings

  has_many :raters, :through => :ratings, :source => :rater

  def avg
    self_ratings = Rating.where(:restaurant_id => self.id)
    self_ratings.average(:stars) || 3.to_f
  end

  def review_count
    Rating.where(:restaurant_id => self.id).count || 0
  end
end

Restrev/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email

  validates_presence_of :name, :email
  validates_format_of :email,
   :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  has_many :ratings

  has_many :rateds, :through => :ratings, :source => :rated

  def num_rated
    Rating.where(:user_id => self.id).count
  end
end

Restrev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
  def current_user
    @current_user = User.find(1)
  end
end

Restrev/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:id])
    @rating = Rating.new
  end

  def create
    params[:rating][:user_id] = current_user.id
    restaurant = params[:restaurant_id]
    params[:rating][:restaurant_id] = params[:restaurant_id].to_i
    @rating = Rating.new(params[:rating])
    if @rating.save!
      redirect_to restaurant_path(restaurant)
    else
      flash[:errors] = @rating.errors.full_messages
      render :new
    end
  end

  def edit
    @rating = Rating.find_by_restaurant_id_and_user_id(params[:restaurant_id], current_user.id)
  end

  def update
    @rating = Rating.find_by_restaurant_id_and_user_id(params[:restaurant_id], current_user.id)
    restaurant = params[:restaurant_id]
    if @rating.update_attributes!(params[:rating])
      redirect_to restaurant_path(restaurant)
    else
      flash[:errors] = @rating.errors.full_messages
      render
    end
  end
end

Restrev/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    if params[:order]
      if ((params[:order] == "name DESC") || (params[:order] == "name ASC"))
        @restaurants = Restaurant.order(params[:order])
      elsif params[:order] == ("count DESC")
        @restaurants = Restaurant.all.sort { |a,b| b.review_count <=> a.review_count }
      elsif params[:order] == ("count ASC")
        @restaurants = Restaurant.all.sort { |a,b| a.review_count <=> b.review_count }
      elsif params[:order] == ("stars DESC")
        @restaurants = Restaurant.all.sort { |a,b| b.avg <=> a.avg }
      elsif params[:order] == ("stars ASC")
        @restaurants = Restaurant.all.sort { |a,b| a.avg <=> b.avg }
      end
    else
      params[:order] = "name DESC"
      @restaurants = Restaurant.order(params[:order])
    end
    render :index
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = User.new(params[:restaurant])
    if @restaurant.save!
      redirect_to restaurant_path(@restaurant)
    else
      flash[:errors] = @restaurant.errors.full_messages
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    prev_rating = Rating.where(:user_id => current_user.id, :restaurant_id => @restaurant.id) || nil
    @prev_rating = prev_rating[0]
    @current_user = current_user
  end
end

Restrev/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save!
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

Restrev/app/helpers/application_helper.rb
module ApplicationHelper
end

Restrev/app/helpers/ratings_helper.rb
module RatingsHelper
end

Restrev/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

Restrev/app/helpers/users_helper.rb
module UsersHelper
end

Restrev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restrev</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <%= content_tag :div, msg, :class => "flash_#{name}" %>
	  <% end %>
	<% end %>

<%= yield %>

</body>
</html>

Restrev/app/views/restaurants/index.html.erb
<h3>Restaurants</h3>

<h4><%= link_to "Users", users_path %></h4>

<form action="/restaurants" method="get">
	<h5>Sort by: <select id="order" name="order">
		<option value="" default>Choose sort parameter</option>
		<option value="name DESC">Name Z-A</option>
		<option value="name ASC">Name A-Z</option>
		<option value="count DESC">Most reviews</option>
		<option value="count ASC">Least reviews</option>
		<option value="stars DESC">Most stars</option>
		<option value="stars ASC">Least stars</option>
	</select></h5>
</form>

<% @restaurants.each do |restaurant| %>
	<h4><%= restaurant.name %></h4>
	<h4>Number of ratings: <%= restaurant.review_count %></h4>
	<h4>Average rating: <%= restaurant.avg %></h4>
	<h4><%= link_to "More on this restaurant", restaurant_path(restaurant) %></h4>
	<hr>
<% end %>

Restrev/app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %><h3>

<%= link_to "Index", restaurants_path %>

<h4>Average rating: <%= @restaurant.avg.to_f %></h4>

<% unless @prev_rating %>

	<form id="rest" action="/restaurants/<%= @restaurant.id %>/ratings" method="post">
		<h5>Stars: <select name="rating[stars]">
			<% 1.upto(5) do |i| %>
				<option value="<%= i %>"><%= i %></option>
			<% end %>
		</select></h5>

		<textarea name="rating[details]" form="rest" placeholder="Enter comment here..."></textarea><br>
		<input type="submit" value="Rate It">
	</form>
<% else %>
	<form id="rest" action="/restaurants/<%= @restaurant.id %>/ratings/<%= @prev_rating.id %>" method="post">
		<input type="hidden" name="_method" value="PUT">
		<h5>Stars: <select name="rating[stars]">
			<% 1.upto(5) do |i| %>
				<option value="<%= i %>"
				  <% if @prev_rating.stars == i %>
				    <%= 'selected' %>
					<% end %>>
					<%= i %>
				</option>
			<% end %>
		</select></h5>

		<textarea name="rating[details]" form="rest"><%= @prev_rating.details %></textarea><br>
		<input type="submit" value="Update">
	</form>

<% end %>

<% @restaurant.ratings.each do |rating| %>
	<h4>Stars: <%= rating.stars %></h4>
	<h4>Comment: <%= rating.details %></h4>
	<h4>Rated by: <%= rating.rater.name %></h4>
	<hr>
<% end %>

Restrev/app/views/users/index.html.erb
<h3>Users</h3>

<h4><%= link_to "Restaurants", restaurants_path %></h4>

<% @users.each do |user| %>
	<h4>Name: <%= user.name %></h4>
	<h4>Email: <%= user.email %></h4>
	<h4>Number of reviews: <%= user.num_rated %></h4>
	<h4><%= link_to "More on this user", user_path(user) %></h4>
	<hr>
<% end %>

Restrev/app/views/users/show.html.erb
<h3><%= @user.name %><h3>

<%= link_to "Index", users_path %>

<% @user.ratings.each do |rating| %>
	<h4>Restaurant name: <%= rating.rated.name %></h4>
	<h4>Stars: <%= rating.stars %></h4>
	<h4>Comment: <%= rating.details %></h4>
 	<h4><%= link_to "More on this restaurant", restaurant_path(rating.rated) %></h4>
	<hr>
	<br>
<% end %>